languageCode = "en-us"
title = "twobiers"
defaultcontentlanguage = "en"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true

[pagination]
  pagerSize = 20

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]

[frontmatter]
	date = [":default", ":filename", ":fileModTime"]

[security]
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']