[goldmark]
[goldmark.renderer]
  unsafe = true

[goldmark.extensions]
[goldmark.extensions.extras.mark]
  enable = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4

[asciidocExt]
  extensions = ['asciidoctor-chroma']
  trace = true
  verbose = true
[asciidocExt.attributes]
  source-highlighter = 'chroma'